package com.example.cookeasy.singleton

import com.example.cookeasy.dataClasses.Ingrediente
import com.example.cookeasy.dataClasses.Instruccion
import com.example.cookeasy.dataClasses.Receta

object RecetasData {

    val listaDeRecetas = mutableListOf(
        // -------------------- APERITIVOS --------------------
        Receta(
            "1", "Ensalada César", "Aperitivos",
            "https://www.goodnes.com/sites/g/files/jgfbjl321/files/srh_recipes/755f697272cbcdc6e5df2adb44b1b705.jpg",
            "Fácil", "15 min",
            listOf(
                Ingrediente("Lechuga romana", "1 unidad"),
                Ingrediente("Pollo a la plancha", "100 g"),
                Ingrediente("Pan tostado", "1 taza"),
                Ingrediente("Queso parmesano", "al gusto")
            ),
            listOf(
                Instruccion(1, "Corta la lechuga y el pollo en trozos pequeños."),
                Instruccion(2, "Agrega los crutones y el queso parmesano."),
                Instruccion(3, "Añade la salsa César y mezcla bien antes de servir.")
            ),
            esFavorito = false
        ),

        Receta("2", "Bruschetta", "Aperitivos",
            "https://www.sanpellegrino.com/es/sites/g/files/xknfdk2326/files/styles/amp_1200x900_4_3/public/bruschetta_0.jpg.webp?itok=KrEQiHy2",
            "Fácil", "10 min",
            listOf(Ingrediente("Pan baguette", "1 unidad"),
                Ingrediente("Tomate", "2 unidades"),
                Ingrediente("Albahaca", "al gusto"),
                Ingrediente("Aceite de oliva", "1 cucharada")),
            listOf(Instruccion(1, "Corta el pan en rebanadas y tuéstalo."),
                Instruccion(2, "Pica los tomates y mezcla con albahaca y aceite."),
                Instruccion(3, "Coloca la mezcla sobre el pan y sirve.")),
            esFavorito = false),

        Receta("3", "Rollitos de jamón y queso", "Aperitivos",
            "https://i.ytimg.com/vi/zM7QkQLjTQA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLByBOcqZcLdngKHXo2Rgg3525sddA",
            "Fácil", "15 min",
            listOf(Ingrediente("Jamón", "4 lonchas"),
                Ingrediente("Queso", "4 lonchas"),
                Ingrediente("Pan de molde", "4 unidades")),
            listOf(Instruccion(1, "Coloca el queso sobre el jamón y enrolla."),
                Instruccion(2, "Corta en porciones y sirve.")),
            esFavorito = false),

        Receta("4", "Dip de espinaca", "Aperitivos",
            "https://cielitorosado.com/wp-content/uploads/2022/05/Dip-de-Espinacas-sm.jpg",
            "Media", "20 min",
            listOf(Ingrediente("Espinaca", "200 g"),
                Ingrediente("Crema de leche", "100 ml"),
                Ingrediente("Queso crema", "100 g")),
            listOf(Instruccion(1, "Cocina la espinaca y mezcla con la crema y el queso."),
                Instruccion(2, "Hornea 10 minutos y sirve caliente.")),
            esFavorito = true),

        Receta("5", "Tostadas de aguacate", "Aperitivos",
            "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/9095F1E1-5407-4953-9228-49AC7AAA8288/Derivates/b183ba61-d10f-4b04-85a6-22a056371b7b.jpg",
            "Fácil", "10 min",
            listOf(Ingrediente("Pan integral", "2 rebanadas"),
                Ingrediente("Aguacate", "1 unidad"),
                Ingrediente("Limón", "1 cucharadita")),
            listOf(Instruccion(1, "Tostar el pan."),
                Instruccion(2, "Machacar el aguacate con limón y untar sobre el pan.")),
            esFavorito = true),

        // -------------------- PLATO FUERTE --------------------
        Receta("6", "Pasta Alfredo", "Plato fuerte",
            "https://www.recetasnestle.com.ec/sites/default/files/styles/recipe_detail_desktop/public/2022-10/pasta-alfredo_0.jpg",
            "Media", "30 min",
            listOf(Ingrediente("Pasta fettuccine", "200 g"),
                Ingrediente("Mantequilla", "2 cucharadas"),
                Ingrediente("Crema de leche", "1 taza"),
                Ingrediente("Queso parmesano", "1/2 taza")),
            listOf(Instruccion(1, "Cocina la pasta según las instrucciones del paquete."),
                Instruccion(2, "Derrite la mantequilla y añade la crema de leche."),
                Instruccion(3, "Agrega el queso parmesano y mezcla hasta obtener una salsa cremosa."),
                Instruccion(4, "Incorpora la pasta y mezcla bien antes de servir.")),
            esFavorito = false),

        Receta("7", "Pollo al horno con papas", "Plato fuerte",
            "https://www.simplyrecipes.com/thmb/pollo_horno_papas.jpg",
            "Media", "60 min",
            listOf(Ingrediente("Pollo", "1 kg"),
                Ingrediente("Papas", "500 g"),
                Ingrediente("Aceite", "2 cucharadas"),
                Ingrediente("Especias", "al gusto")),
            listOf(Instruccion(1, "Sazona el pollo con especias."),
                Instruccion(2, "Hornea con las papas a 180°C por 50 minutos.")),
            esFavorito = true),

        Receta("8", "Lasaña", "Plato fuerte",
            "https://www.simplyrecipes.com/thmb/lasana.jpg",
            "Difícil", "90 min",
            listOf(Ingrediente("Pasta para lasaña", "200 g"),
                Ingrediente("Carne molida", "300 g"),
                Ingrediente("Queso mozzarella", "200 g"),
                Ingrediente("Salsa de tomate", "200 ml")),
            listOf(Instruccion(1, "Cocina la carne y mezcla con salsa."),
                Instruccion(2, "Arma capas de pasta, carne y queso."),
                Instruccion(3, "Hornea 45 minutos a 180°C.")),
            esFavorito = false),

        Receta("9", "Salmón a la plancha", "Plato fuerte",
            "https://www.simplyrecipes.com/thmb/salmon_plancha.jpg",
            "Media", "25 min",
            listOf(Ingrediente("Salmón", "2 filetes"),
                Ingrediente("Limón", "1 unidad"),
                Ingrediente("Aceite", "1 cucharada")),
            listOf(Instruccion(1, "Marinar el salmón con limón y aceite."),
                Instruccion(2, "Cocinar a la plancha 10 minutos por lado.")),
            esFavorito = true),

        Receta("10", "Arroz con pollo", "Plato fuerte",
            "https://www.simplyrecipes.com/thmb/arroz_pollo.jpg",
            "Media", "40 min",
            listOf(Ingrediente("Arroz", "200 g"),
                Ingrediente("Pollo", "300 g"),
                Ingrediente("Vegetales", "100 g")),
            listOf(Instruccion(1, "Cocinar el pollo."),
                Instruccion(2, "Agregar arroz y vegetales."),
                Instruccion(3, "Cocinar hasta que el arroz esté listo.")),
            esFavorito = false),

        // -------------------- DESAYUNO --------------------
        Receta("11", "Pancakes", "Desayuno",
            "https://www.simplyrecipes.com/thmb/pancakes.jpg",
            "Fácil", "20 min",
            listOf(Ingrediente("Harina", "1 taza"),
                Ingrediente("Leche", "1 taza"),
                Ingrediente("Huevo", "1 unidad"),
                Ingrediente("Miel", "al gusto")),
            listOf(Instruccion(1, "Mezclar los ingredientes."),
                Instruccion(2, "Cocinar en sartén antiadherente hasta dorar.")),
            esFavorito = true),

        Receta("12", "Tostadas francesas", "Desayuno",
            "https://www.simplyrecipes.com/thmb/tostadas_francesas.jpg",
            "Fácil", "15 min",
            listOf(Ingrediente("Pan", "2 rebanadas"),
                Ingrediente("Huevo", "1 unidad"),
                Ingrediente("Leche", "1/4 taza")),
            listOf(Instruccion(1, "Batir huevo y leche."),
                Instruccion(2, "Remojar pan y cocinar en sartén.")),
            esFavorito = false),

        Receta("13", "Omelette de queso", "Desayuno",
            "https://www.simplyrecipes.com/thmb/omelette_queso.jpg",
            "Fácil", "10 min",
            listOf(Ingrediente("Huevos", "2 unidades"),
                Ingrediente("Queso", "50 g"),
                Ingrediente("Sal y pimienta", "al gusto")),
            listOf(Instruccion(1, "Batir huevos con sal y pimienta."),
                Instruccion(2, "Agregar queso y cocinar en sartén.")),
            esFavorito = true),

        Receta("14", "Smoothie de frutas", "Desayuno",
            "https://www.simplyrecipes.com/thmb/smoothie_frutas.jpg",
            "Fácil", "5 min",
            listOf(Ingrediente("Frutas mixtas", "200 g"),
                Ingrediente("Yogur", "100 ml"),
                Ingrediente("Miel", "1 cucharadita")),
            listOf(Instruccion(1, "Licuar todos los ingredientes."),
                Instruccion(2, "Servir frío.")),
            esFavorito = true),

        Receta("15", "Bagel con aguacate", "Desayuno",
            "https://www.simplyrecipes.com/thmb/bagel_aguacate.jpg",
            "Fácil", "10 min",
            listOf(Ingrediente("Bagel", "1 unidad"),
                Ingrediente("Aguacate", "1 unidad")),
            listOf(Instruccion(1, "Tostar bagel."),
                Instruccion(2, "Untar aguacate.")),
            esFavorito = false),

        // -------------------- POSTRES --------------------
        Receta("16", "Flan de vainilla", "Postres",
            "https://cdn7.kiwilimon.com/recetaimagen/37033/640x640/46357.jpg",
            "Fácil", "45 min",
            listOf(Ingrediente("Leche condensada", "1 lata"),
                Ingrediente("Huevos", "4 unidades"),
                Ingrediente("Azúcar", "1 taza"),
                Ingrediente("Vainilla", "1 cucharadita")),
            listOf(Instruccion(1, "Precalienta el horno a 180°C."),
                Instruccion(2, "Derrite el azúcar hasta formar caramelo."),
                Instruccion(3, "Licúa los ingredientes y vierte sobre el caramelo."),
                Instruccion(4, "Hornea a baño maría por 40 min.")),
            esFavorito = true),

        Receta("17", "Pastel de chocolate", "Postres",
            "https://www.simplyrecipes.com/thmb/pastel_chocolate.jpg",
            "Media", "60 min",
            listOf(Ingrediente("Harina", "2 tazas"),
                Ingrediente("Cacao en polvo", "1 taza"),
                Ingrediente("Huevos", "3 unidades"),
                Ingrediente("Azúcar", "1 taza")),
            listOf(Instruccion(1, "Mezclar ingredientes secos y húmedos."),
                Instruccion(2, "Hornear 35 min a 180°C.")),
            esFavorito = true),

        Receta("18", "Helado casero", "Postres",
            "https://www.simplyrecipes.com/thmb/helado_casero.jpg",
            "Difícil", "120 min",
            listOf(Ingrediente("Leche", "1 taza"),
                Ingrediente("Crema", "1 taza"),
                Ingrediente("Azúcar", "1/2 taza")),
            listOf(Instruccion(1, "Mezclar todos los ingredientes."),
                Instruccion(2, "Congelar y remover cada 30 min por 2 horas.")),
            esFavorito = false),

        Receta("19", "Brownies", "Postres",
            "https://www.simplyrecipes.com/thmb/brownies.jpg",
            "Media", "40 min",
            listOf(Ingrediente("Chocolate", "200 g"),
                Ingrediente("Mantequilla", "100 g"),
                Ingrediente("Harina", "1 taza"),
                Ingrediente("Huevos", "2 unidades")),
            listOf(Instruccion(1, "Derretir chocolate y mantequilla."),
                Instruccion(2, "Mezclar con harina y huevos."),
                Instruccion(3, "Hornear 25 min a 180°C.")),
            esFavorito = true),

        Receta("20", "Cheesecake", "Postres",
            "https://www.simplyrecipes.com/thmb/cheesecake.jpg",
            "Difícil", "90 min",
            listOf(Ingrediente("Queso crema", "500 g"),
                Ingrediente("Galletas", "200 g"),
                Ingrediente("Mantequilla", "100 g")),
            listOf(Instruccion(1, "Triturar galletas y mezclar con mantequilla."),
                Instruccion(2, "Hornear la base, añadir crema de queso y refrigerar 4 horas.")),
            esFavorito = true),

        // -------------------- BEBIDAS --------------------
        Receta("21", "Limonada frappé", "Bebidas",
            "https://cdn0.recetasgratis.net/es/posts/0/6/2/limonada_frappe_10260_orig.jpg",
            "Fácil", "10 min",
            listOf(Ingrediente("Limones", "3 unidades"),
                Ingrediente("Agua fría", "2 tazas"),
                Ingrediente("Azúcar", "al gusto"),
                Ingrediente("Hielo", "1 taza")),
            listOf(Instruccion(1, "Exprime los limones."),
                Instruccion(2, "Licúa con agua, azúcar e hielo."),
                Instruccion(3, "Sirve al instante.")),
            esFavorito = true),

        Receta("22", "Smoothie de fresa", "Bebidas",
            "https://www.simplyrecipes.com/thmb/smoothie_fresa.jpg",
            "Fácil", "5 min",
            listOf(Ingrediente("Fresas", "200 g"),
                Ingrediente("Yogur", "100 ml"),
                Ingrediente("Miel", "1 cucharadita")),
            listOf(Instruccion(1, "Licuar todos los ingredientes."),
                Instruccion(2, "Servir frío.")),
            esFavorito = false),

        Receta("23", "Café frappé", "Bebidas",
            "https://www.simplyrecipes.com/thmb/cafe_frappe.jpg",
            "Fácil", "10 min",
            listOf(Ingrediente("Café", "1 taza"),
                Ingrediente("Hielo", "1 taza"),
                Ingrediente("Leche", "100 ml"),
                Ingrediente("Azúcar", "al gusto")),
            listOf(Instruccion(1, "Preparar café y mezclar con hielo y leche."),
                Instruccion(2, "Endulzar al gusto y servir.")),
            esFavorito = true),

        Receta("24", "Té helado", "Bebidas",
            "https://www.simplyrecipes.com/thmb/te_helado.jpg",
            "Fácil", "5 min",
            listOf(Ingrediente("Té negro", "2 bolsitas"),
                Ingrediente("Agua", "500 ml"),
                Ingrediente("Limón", "1 rodaja"),
                Ingrediente("Hielo", "al gusto")),
            listOf(Instruccion(1, "Hervir agua y preparar el té."),
                Instruccion(2, "Enfriar, agregar limón y hielo."),
                Instruccion(3, "Servir.")),
            esFavorito = false),

        Receta("25", "Jugo de naranja", "Bebidas",
            "https://www.simplyrecipes.com/thmb/jugo_naranja.jpg",
            "Fácil", "5 min",
            listOf(Ingrediente("Naranjas", "3 unidades")),
            listOf(Instruccion(1, "Exprimir las naranjas."),
                Instruccion(2, "Servir al instante.")),
            esFavorito = true)
    )
}